// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDmOwElAl8ploSqyIclTNkrNGtyG-SVJc',
    appId: '1:358029438538:web:ef04606b90715959cd00b3',
    messagingSenderId: '358029438538',
    projectId: 'procaryote-1',
    authDomain: 'procaryote-1.firebaseapp.com',
    databaseURL: "https://procaryote-1.firebaseio.com",
//    databaseURL: 'https://procaryote-1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'procaryote-1.appspot.com',
    measurementId: 'G-BY7VPVQTYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3RTIoOgXvL-6O1aQhrN4FrAefydTpH08',
    appId: '1:358029438538:android:0cfc551330317164cd00b3',
    messagingSenderId: '358029438538',
    projectId: 'procaryote-1',
    databaseURL: "https://procaryote-1.firebaseio.com",
//    databaseURL: 'https://procaryote-1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'procaryote-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUcCiIgXJ05KFBV9Y0KOAQMzgdXDQrp88',
    appId: '1:358029438538:ios:07294703a535e117cd00b3',
    messagingSenderId: '358029438538',
    projectId: 'procaryote-1',
    databaseURL: "https://procaryote-1.firebaseio.com",
//    databaseURL: 'https://procaryote-1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'procaryote-1.appspot.com',
    iosClientId:
        '358029438538-jamtq61jiehtpg733h3uu0u2ckp7gssl.apps.googleusercontent.com',
    iosBundleId: 'com.procaryote.healthbook',
  );
}
